#ifndef als_bindings_h
#define als_bindings_h

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>


typedef struct ALS_ResourceSet ALS_ResourceSet;

typedef struct ALS_StateListener ALS_StateListener;

typedef struct ALS_Unit ALS_Unit;

typedef struct ALS_UnitType ALS_UnitType;

typedef struct ALS_OrderList ALS_OrderList;

typedef struct ALS_IdList ALS_IdList;

typedef struct ALS_World ALS_World;

typedef float (*ALS_DfuncType)(uint8_t, uint8_t);

typedef void (*ALS_CInitHandle)(void);

typedef void (*ALS_CTurnHandle)(struct ALS_World*, struct ALS_OrderList*);

void alsBeginS_Display(int32_t sw,
                       int32_t sh,
                       const char *t,
                       struct ALS_ResourceSet *rs,
                       struct ALS_World *w);

void alsBegin_Display(int32_t sw,
                      int32_t sh,
                      bool vsync,
                      uint32_t fps,
                      const char *t,
                      struct ALS_ResourceSet *rs,
                      struct ALS_World *w,
                      struct ALS_StateListener *sl,
                      float mvl);

void alsBindDamageFunc(struct ALS_World *w, ALS_DfuncType f);

void alsBindInit(struct ALS_StateListener *sl, ALS_CInitHandle f);

void alsBindTurn(struct ALS_StateListener *sl, ALS_CTurnHandle f);

struct ALS_World *alsBlank_World(void);

void alsCreateStatic(struct ALS_World *w, uint8_t tex_id, int32_t cx, int32_t cy);

void alsDefAnim(struct ALS_UnitType *u,
                uint32_t fw,
                uint32_t fh,
                uint8_t frn,
                uint32_t cfx,
                uint32_t cfy,
                float fr,
                bool flip);

struct ALS_IdList *alsIdList(const struct ALS_World *w);

bool alsLoadMap(struct ALS_World *w, const char *fpath);

void alsMapFont(struct ALS_ResourceSet *rs, uint8_t id, const char *path);

void alsMapMusic(struct ALS_ResourceSet *rs, uint8_t id, const char *path);

void alsMapSound(struct ALS_ResourceSet *rs, uint8_t id, const char *path);

void alsMapTexture(struct ALS_ResourceSet *rs, uint8_t id, const char *path);

void alsMapTextureRegion(struct ALS_ResourceSet *rs,
                         uint8_t tid,
                         uint8_t parent_id,
                         float x,
                         float y,
                         float w,
                         float h);

struct ALS_ResourceSet *alsNewResourceSet(void);

struct ALS_StateListener *alsNewStateListener(void);

struct ALS_UnitType *alsNewUnitType(uint8_t tid,
                                    const char *name,
                                    float health,
                                    float mov_rate,
                                    uint8_t movt,
                                    uint8_t ran,
                                    float adur);

void alsRegisterUnitType(struct ALS_World *w, struct ALS_UnitType *u, uint8_t id);

void alsSetUnitInfo(struct ALS_UnitType *u, const char *s);

uint8_t alsSpawnUnit(struct ALS_World *w,
                     uint8_t tid,
                     int32_t tx,
                     int32_t ty,
                     int32_t tint,
                     bool plr);

bool alsTilePermAt(const struct ALS_World *w, int32_t x, int32_t y);

bool alsVerifyUID(const struct ALS_World *w, uint8_t uid);

void alsnFreeVec(struct ALS_IdList *v);

float alsnGetUnitHealth(struct ALS_World *w, uint8_t uid);

float alsnGetUnitX(const struct ALS_Unit *w);

float alsnGetUnitY(const struct ALS_Unit *w);

bool alsnIsUnitFoe(const struct ALS_Unit *uref);

void alsnPushAttackOrder(struct ALS_OrderList *i,
                         uint8_t uid,
                         uint8_t target,
                         int32_t tx,
                         int32_t ty);

void alsnPushMoveOrder(struct ALS_OrderList *i, uint8_t uid, int32_t tx, int32_t ty);

const struct ALS_Unit *alsnUnitRef(struct ALS_World *w, uint8_t uid);

uint8_t alsnVecAt(const struct ALS_IdList *u, size_t elm);

size_t alsnVecLen(const struct ALS_IdList *u);

void alsFreeWorld(struct ALS_World *w);
void alsFreeResourceSet(struct ALS_ResourceSet *w);
void alsFreeUnitType(struct ALS_UnitType *w);

#endif /* als_bindings_h */
